### ISSUE TITLE
Add the paper

### ISSUE THREAD

**Issue by crawfordcomeaux** [jmid/efftester#1]
Would you be willing to add the pdf of the paper to this project?

**Comment by jmid** [comment]
Added a paper link to the full version. Thanks for your interest in this work.

**Comment by jmid** [comment]
@crawfordcomeaux I've now put another copy up here: http://people.compute.dtu.dk/janmi/Midtgaard-al:ICFP17-full.pdf  (Hacker News really blew the fuses repeatedly on my hosting)
